services:
    nginx:
        build:
            context: .
            dockerfile: .docker/nginx.dockerfile
            args:
                UID: "${UID:-1000}"
                GID: "${GID:-1000}"
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        depends_on:
            - php
            - postgres
        networks:
            - laravel


    php:
        build:
            context: .
            dockerfile: .docker/php.root.dockerfile
            args:
                UID: "${UID:-1000}"
                GID: "${GID:-1000}"
        volumes:
            - ./:/var/www/html
        networks:
            - laravel

    postgres:
        image: postgres:latest
        container_name: postgres
        restart: unless-stopped
        tty: true
        ports:
            - "15432:5432"
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=user
            - POSTGRES_DB=chatgpt
            - POSTGRES_ROOT_PASSWORD=password
            - SERVICE_NAME=chatgpt
            - SERVICE_TAGS=dev
        volumes:
            - ./postgres:/var/lib/postgresql/data
        networks:
            - laravel

networks:
    laravel:
