services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=chatgpt
      - POSGTRES_ROOT_PASSWORD=password # тут кстати опечатка! POSGTRES → POSTGRES
      - SERVICE_NAME=chatgpt
      - SERVICE_TAGS=dev
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:
